# fly.toml app configuration file generated for gifhub on 2023-06-19T17:48:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gifhub"
primary_region = "den"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "gifhub.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
